In [2]:
data = pd.read_csv("sampled_data_translated.csv")

In [3]:
data

,tweet_id,language,tweet_type,original_tweet_id,tweet_text,user_id,place_id,tweet_creation,hashtags,mentions,...,listed_count,verified,url,md,place_name,place_full_name,country,country_code,place_type,centroid
0,76,en,Original,0,kinda twttring around and such,13,0,2006-03-22 00:00:51+00:00,NaN,NaN,...,18698,True,https://t.co/gLACV0KABc,2006_1,NaN,NaN,NaN,NaN,NaN,NaN
1,175531324168351745,en,Original,0,"""Hydrogen peroxide added in small amounts to d...",503368661,0,2012-03-02 10:41:43+00:00,NaN,NaN,...,0,False,NaN,2012_1,NaN,NaN,NaN,NaN,NaN,NaN
2,286039083011170304,ja,Original,0,"â€˜Kato Shahi, love you! in TV, bring the topic ...",436851409,0,2013-01-01 09:20:06+00:00,NaN,NaN,...,19,False,NaN,2013_1,NaN,NaN,NaN,NaN,NaN,NaN
3,286462102284148738,ca,Original,0,Hydrogen peroxide vapor enhances hospital disi...,119054506,0,2013-01-02 13:21:02+00:00,NaN,NaN,...,19,False,http://t.co/qJFcj5iCFI,2013_1,NaN,NaN,NaN,NaN,NaN,NaN
4,286834468126347264,ja,Original,0,CNIC News 2011/10/13 3 aircraft explosion is a...,88442750,0,2013-01-03 14:00:40+00:00,NaN,NaN,...,30,False,https://t.co/zHCRTyoNby,2013_1,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10005,1608989763708801025,ja,Reply,1608989365975547904,@gomaaburaseizin I laughed and laughed how muc...,1605132914915946497,0,2022-12-31 00:53:47+00:00,NaN,|gomaaburaseizin,...,6,False,https://t.co/KWlmMR1P59,2022_2,NaN,NaN,NaN,NaN,NaN,NaN
10006,1609073470541041665,qme,Reply,1609064727212326917,@irgxf @adndotcom @AlaskaBeacon https://t.co/j...,58257535,0,2022-12-31 06:26:25+00:00,NaN,|irgxf|adndotcom|AlaskaBeacon,...,3,False,https://t.co/QhXGsfXueh,2022_2,NaN,NaN,NaN,NaN,NaN,NaN
10007,1609160340889010177,en,Original,0,Cummins Participates in the 6th Foshan Hydroge...,1059819391,0,2022-12-31 12:11:36+00:00,NaN,NaN,...,0,False,NaN,2022_2,NaN,NaN,NaN,NaN,NaN,NaN
10008,1609237428476297216,zxx,Original,0,https://t.co/dOggyMSw5F,173511443,0,2022-12-31 17:17:55+00:00,NaN,NaN,...,30,False,http://t.co/TLti8890Lf,2022_2,NaN,NaN,NaN,NaN,NaN,NaN
10009,1609334796622385152,en,Reply,1605799898909052928,@Victori47392774 @Wardmaryb @JohnStossel Hydro...,1149482665780731905,0,2022-12-31 23:44:50+00:00,NaN,|Victori47392774|Wardmaryb|JohnStossel,...,2,False,NaN,2022_2,NaN,NaN,NaN,NaN,NaN,NaN

### Language Detection and Translation

### Text Cleaning and Tokenization

In [5]:
#If you haven't downloaded this segmentation model, open the comments and run the code. If you have downloaded it, you don't need to run it anymore

# nltk.download('punkt')

In [6]:
# Function to clean and tokenize tweets
def clean_tweet(tweet):
    # Remove URLs
    tweet = re.sub(r"http\S+|www\S+|https\S+", '', tweet, flags=re.MULTILINE)
    # Remove emojis and non-ASCII characters
    tweet = re.sub(r'[^\x00-\x7F]+', '', tweet)
    # Remove punctuation
    tweet = re.sub(r'[^\w\s]', ' ', tweet)  # ç§»é™¤æ ‡ç‚¹
    # Remove extra spaces
    tweet = re.sub(r'\s+', ' ', tweet).strip()  # ç§»é™¤å¤šä½™ç©ºæ ¼
    # Lowercase
    tweet = tweet.lower()
    return tweet

In [7]:
data['cleaned_tweet'] = data['tweet_text'].apply(clean_tweet)
data['tweet_text_tokens'] = data['cleaned_tweet'].apply(word_tokenize)

In [8]:
data

,tweet_id,language,tweet_type,original_tweet_id,tweet_text,user_id,place_id,tweet_creation,hashtags,mentions,...,url,md,place_name,place_full_name,country,country_code,place_type,centroid,cleaned_tweet,tweet_text_tokens
0,76,en,Original,0,kinda twttring around and such,13,0,2006-03-22 00:00:51+00:00,NaN,NaN,...,https://t.co/gLACV0KABc,2006_1,NaN,NaN,NaN,NaN,NaN,NaN,kinda twttring around and such,"[kinda, twttring, around, and, such]"
1,175531324168351745,en,Original,0,"""Hydrogen peroxide added in small amounts to d...",503368661,0,2012-03-02 10:41:43+00:00,NaN,NaN,...,NaN,2012_1,NaN,NaN,NaN,NaN,NaN,NaN,hydrogen peroxide added in small amounts to dr...,"[hydrogen, peroxide, added, in, small, amounts..."
2,286039083011170304,ja,Original,0,"â€˜Kato Shahi, love you! in TV, bring the topic ...",436851409,0,2013-01-01 09:20:06+00:00,NaN,NaN,...,NaN,2013_1,NaN,NaN,NaN,NaN,NaN,NaN,kato shahi love you in tv bring the topic of h...,"[kato, shahi, love, you, in, tv, bring, the, t..."
3,286462102284148738,ca,Original,0,Hydrogen peroxide vapor enhances hospital disi...,119054506,0,2013-01-02 13:21:02+00:00,NaN,NaN,...,http://t.co/qJFcj5iCFI,2013_1,NaN,NaN,NaN,NaN,NaN,NaN,hydrogen peroxide vapor enhances hospital disi...,"[hydrogen, peroxide, vapor, enhances, hospital..."
4,286834468126347264,ja,Original,0,CNIC News 2011/10/13 3 aircraft explosion is a...,88442750,0,2013-01-03 14:00:40+00:00,NaN,NaN,...,https://t.co/zHCRTyoNby,2013_1,NaN,NaN,NaN,NaN,NaN,NaN,cnic news 2011 10 13 3 aircraft explosion is a...,"[cnic, news, 2011, 10, 13, 3, aircraft, explos..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10005,1608989763708801025,ja,Reply,1608989365975547904,@gomaaburaseizin I laughed and laughed how muc...,1605132914915946497,0,2022-12-31 00:53:47+00:00,NaN,|gomaaburaseizin,...,https://t.co/KWlmMR1P59,2022_2,NaN,NaN,NaN,NaN,NaN,NaN,gomaaburaseizin i laughed and laughed how much...,"[gomaaburaseizin, i, laughed, and, laughed, ho..."
10006,1609073470541041665,qme,Reply,1609064727212326917,@irgxf @adndotcom @AlaskaBeacon https://t.co/j...,58257535,0,2022-12-31 06:26:25+00:00,NaN,|irgxf|adndotcom|AlaskaBeacon,...,https://t.co/QhXGsfXueh,2022_2,NaN,NaN,NaN,NaN,NaN,NaN,irgxf adndotcom alaskabeacon,"[irgxf, adndotcom, alaskabeacon]"
10007,1609160340889010177,en,Original,0,Cummins Participates in the 6th Foshan Hydroge...,1059819391,0,2022-12-31 12:11:36+00:00,NaN,NaN,...,NaN,2022_2,NaN,NaN,NaN,NaN,NaN,NaN,cummins participates in the 6th foshan hydroge...,"[cummins, participates, in, the, 6th, foshan, ..."
10008,1609237428476297216,zxx,Original,0,https://t.co/dOggyMSw5F,173511443,0,2022-12-31 17:17:55+00:00,NaN,NaN,...,http://t.co/TLti8890Lf,2022_2,NaN,NaN,NaN,NaN,NaN,NaN,,[]
10009,1609334796622385152,en,Reply,1605799898909052928,@Victori47392774 @Wardmaryb @JohnStossel Hydro...,1149482665780731905,0,2022-12-31 23:44:50+00:00,NaN,|Victori47392774|Wardmaryb|JohnStossel,...,NaN,2022_2,NaN,NaN,NaN,NaN,NaN,NaN,victori47392774 wardmaryb johnstossel hydrogen...,"[victori47392774, wardmaryb, johnstossel, hydr..."

### Sentiment Analysis

In [9]:
analyzer = SentimentIntensityAnalyzer()

In [10]:
# Sentiment Analysis Function
def sentiment_analysis(text):
    scores = analyzer.polarity_scores(text)
    if scores['compound'] >= 0.05:
        return 1    # 'positive'
    elif scores['compound'] <= -0.05:
        return -1   # 'negative'
    else:
        return 0    # 'neutral'

In [11]:
data['sentiment'] = data['tweet_text'].apply(sentiment_analysis)

In [12]:
data

,tweet_id,language,tweet_type,original_tweet_id,tweet_text,user_id,place_id,tweet_creation,hashtags,mentions,...,md,place_name,place_full_name,country,country_code,place_type,centroid,cleaned_tweet,tweet_text_tokens,sentiment
0,76,en,Original,0,kinda twttring around and such,13,0,2006-03-22 00:00:51+00:00,NaN,NaN,...,2006_1,NaN,NaN,NaN,NaN,NaN,NaN,kinda twttring around and such,"[kinda, twttring, around, and, such]",0
1,175531324168351745,en,Original,0,"""Hydrogen peroxide added in small amounts to d...",503368661,0,2012-03-02 10:41:43+00:00,NaN,NaN,...,2012_1,NaN,NaN,NaN,NaN,NaN,NaN,hydrogen peroxide added in small amounts to dr...,"[hydrogen, peroxide, added, in, small, amounts...",-1
2,286039083011170304,ja,Original,0,"â€˜Kato Shahi, love you! in TV, bring the topic ...",436851409,0,2013-01-01 09:20:06+00:00,NaN,NaN,...,2013_1,NaN,NaN,NaN,NaN,NaN,NaN,kato shahi love you in tv bring the topic of h...,"[kato, shahi, love, you, in, tv, bring, the, t...",1
3,286462102284148738,ca,Original,0,Hydrogen peroxide vapor enhances hospital disi...,119054506,0,2013-01-02 13:21:02+00:00,NaN,NaN,...,2013_1,NaN,NaN,NaN,NaN,NaN,NaN,hydrogen peroxide vapor enhances hospital disi...,"[hydrogen, peroxide, vapor, enhances, hospital...",0
4,286834468126347264,ja,Original,0,CNIC News 2011/10/13 3 aircraft explosion is a...,88442750,0,2013-01-03 14:00:40+00:00,NaN,NaN,...,2013_1,NaN,NaN,NaN,NaN,NaN,NaN,cnic news 2011 10 13 3 aircraft explosion is a...,"[cnic, news, 2011, 10, 13, 3, aircraft, explos...",-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10005,1608989763708801025,ja,Reply,1608989365975547904,@gomaaburaseizin I laughed and laughed how muc...,1605132914915946497,0,2022-12-31 00:53:47+00:00,NaN,|gomaaburaseizin,...,2022_2,NaN,NaN,NaN,NaN,NaN,NaN,gomaaburaseizin i laughed and laughed how much...,"[gomaaburaseizin, i, laughed, and, laughed, ho...",1
10006,1609073470541041665,qme,Reply,1609064727212326917,@irgxf @adndotcom @AlaskaBeacon https://t.co/j...,58257535,0,2022-12-31 06:26:25+00:00,NaN,|irgxf|adndotcom|AlaskaBeacon,...,2022_2,NaN,NaN,NaN,NaN,NaN,NaN,irgxf adndotcom alaskabeacon,"[irgxf, adndotcom, alaskabeacon]",0
10007,1609160340889010177,en,Original,0,Cummins Participates in the 6th Foshan Hydroge...,1059819391,0,2022-12-31 12:11:36+00:00,NaN,NaN,...,2022_2,NaN,NaN,NaN,NaN,NaN,NaN,cummins participates in the 6th foshan hydroge...,"[cummins, participates, in, the, 6th, foshan, ...",0
10008,1609237428476297216,zxx,Original,0,https://t.co/dOggyMSw5F,173511443,0,2022-12-31 17:17:55+00:00,NaN,NaN,...,2022_2,NaN,NaN,NaN,NaN,NaN,NaN,,[],0
10009,1609334796622385152,en,Reply,1605799898909052928,@Victori47392774 @Wardmaryb @JohnStossel Hydro...,1149482665780731905,0,2022-12-31 23:44:50+00:00,NaN,|Victori47392774|Wardmaryb|JohnStossel,...,2022_2,NaN,NaN,NaN,NaN,NaN,NaN,victori47392774 wardmaryb johnstossel hydrogen...,"[victori47392774, wardmaryb, johnstossel, hydr...",-1

### Feature Extraction

In [13]:
#Processing hashtags and mentions columns: Replace NaN with an empty list, separate other content with '|' and convert to a list, remove unnecessary spaces, convert to lowercase for tokenization later
# --- Hashtags ---
# Extract hashtags and create hashtag count
data['hashtags_tokens'] = data['hashtags'].apply(lambda x: [tag.strip().lower() for tag in x.split('|') if tag.strip()] if isinstance(x, str) else [])
data['hashtags_count'] = data['hashtags_tokens'].apply(len)

# --- Mentions ---
# Extract mentions and create mention count
data['mentions_tokens'] = data['mentions'].apply(lambda x: [tag.strip().lower() for tag in x.split('|') if tag.strip()] if isinstance(x, str) else [])
data['mentions_count'] = data['mentions_tokens'].apply(len)

# --- User Influence ---
# Calculate user influence score ( influence = followers_count * (1 + verified) )
data['user_influence'] = data['followers_count'] * (1 + data['verified'])
data['user_influence'].fillna(0, inplace=True)
data['user_influence'] = data['user_influence'].astype(int)

# --- Timing Features ---
# Convert tweet_creation to datetime
data['tweet_creation'] = pd.to_datetime(data['tweet_creation'])
data['tweet_year'] = data['tweet_creation'].dt.year
data['tweet_month'] = data['tweet_creation'].dt.month
data['tweet_days'] = data['tweet_creation'].dt.day
data['tweet_day'] = data['tweet_creation'].dt.dayofweek
data['tweet_hour'] = data['tweet_creation'].dt.hour
data['is_weekend'] = data['tweet_creation'].dt.dayofweek >= 5

In [14]:
# Initialize the SBERT model
model = SentenceTransformer('all-MiniLM-L6-v2')

In [15]:
# Replace NaN values with empty strings in the relevant columns
data['hashtags'] = data['hashtags'].fillna('')
data['mentions'] = data['mentions'].fillna('')
# Encode each tweet into a dense vector representation
data['hashtags_embedding'] = data['hashtags'].apply(lambda x: model.encode(x).tolist())
data['mentions_embedding'] = data['mentions'].apply(lambda x: model.encode(x).tolist())
data['tweet_text_embedding'] = data['tweet_text'].apply(lambda x: model.encode(x).tolist())

In [16]:
data

,tweet_id,language,tweet_type,original_tweet_id,tweet_text,user_id,place_id,tweet_creation,hashtags,mentions,...,user_influence,tweet_year,tweet_month,tweet_days,tweet_day,tweet_hour,is_weekend,hashtags_embedding,mentions_embedding,tweet_text_embedding
0,76,en,Original,0,kinda twttring around and such,13,0,2006-03-22 00:00:51+00:00,,,...,5248566,2006,3,22,2,0,False,"[-0.11883842945098877, 0.04829872027039528, -0...","[-0.11883842945098877, 0.04829872027039528, -0...","[-0.01654781773686409, 0.0477893240749836, 0.0..."
1,175531324168351745,en,Original,0,"""Hydrogen peroxide added in small amounts to d...",503368661,0,2012-03-02 10:41:43+00:00,,,...,46,2012,3,2,4,10,False,"[-0.11883842945098877, 0.04829872027039528, -0...","[-0.11883842945098877, 0.04829872027039528, -0...","[-0.025313112884759903, 0.051009830087423325, ..."
2,286039083011170304,ja,Original,0,"â€˜Kato Shahi, love you! in TV, bring the topic ...",436851409,0,2013-01-01 09:20:06+00:00,,,...,2747,2013,1,1,1,9,False,"[-0.11883842945098877, 0.04829872027039528, -0...","[-0.11883842945098877, 0.04829872027039528, -0...","[-0.07220662385225296, -0.019841067492961884, ..."
3,286462102284148738,ca,Original,0,Hydrogen peroxide vapor enhances hospital disi...,119054506,0,2013-01-02 13:21:02+00:00,,,...,955,2013,1,2,2,13,False,"[-0.11883842945098877, 0.04829872027039528, -0...","[-0.11883842945098877, 0.04829872027039528, -0...","[-0.003000939264893532, -0.010538204573094845,..."
4,286834468126347264,ja,Original,0,CNIC News 2011/10/13 3 aircraft explosion is a...,88442750,0,2013-01-03 14:00:40+00:00,,,...,327,2013,1,3,3,14,False,"[-0.11883842945098877, 0.04829872027039528, -0...","[-0.11883842945098877, 0.04829872027039528, -0...","[-0.01976289041340351, 0.07890097796916962, 0...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10005,1608989763708801025,ja,Reply,1608989365975547904,@gomaaburaseizin I laughed and laughed how muc...,1605132914915946497,0,2022-12-31 00:53:47+00:00,,|gomaaburaseizin,...,536,2022,12,31,5,0,True,"[-0.11883842945098877, 0.04829872027039528, -0...","[0.006109271198511124, 0.162232905626297, -0.0...","[-0.01719362847507, 0.030254265293478966, 0.03..."
10006,1609073470541041665,qme,Reply,1609064727212326917,@irgxf @adndotcom @AlaskaBeacon https://t.co/j...,58257535,0,2022-12-31 06:26:25+00:00,,|irgxf|adndotcom|AlaskaBeacon,...,89,2022,12,31,5,6,True,"[-0.11883842945098877, 0.04829872027039528, -0...","[0.010872884653508663, -0.0415927991271019, -0...","[-0.05069870129227638, 0.01034287828952074, 0...."
10007,1609160340889010177,en,Original,0,Cummins Participates in the 6th Foshan Hydroge...,1059819391,0,2022-12-31 12:11:36+00:00,,,...,2,2022,12,31,5,12,True,"[-0.11883842945098877, 0.04829872027039528, -0...","[-0.11883842945098877, 0.04829872027039528, -0...","[-0.04631892591714859, 0.008540322072803974, -..."
10008,1609237428476297216,zxx,Original,0,https://t.co/dOggyMSw5F,173511443,0,2022-12-31 17:17:55+00:00,,,...,535,2022,12,31,5,17,True,"[-0.11883842945098877, 0.04829872027039528, -0...","[-0.11883842945098877, 0.04829872027039528, -0...","[-0.04486410692334175, -0.006326509173959494, ..."
10009,1609334796622385152,en,Reply,1605799898909052928,@Victori47392774 @Wardmaryb @JohnStossel Hydro...,1149482665780731905,0,2022-12-31 23:44:50+00:00,,|Victori47392774|Wardmaryb|JohnStossel,...,31,2022,12,31,5,23,True,"[-0.11883842945098877, 0.04829872027039528, -0...","[-0.10073011368513107, 0.018242178484797478, -...","[-0.09967131167650223, 0.045538194477558136, -..."

In [17]:
data.to_csv('sampled_data_preprocessed.csv', index=False)